controller_list:
    # - name: arm_position_r
    #   action_ns: follow_joint_trajectory
    #   type: FollowJointTrajectory
    #   joints:
    #       - oberon7_r/azimuth
    #       - oberon7_r/shoulder
    #       - oberon7_r/elbow
    #       - oberon7_r/roll
    #       - oberon7_r/pitch
    #       - oberon7_r/wrist
    # - name: hand_position_r
    #   action_ns: follow_joint_trajectory
    #   type: FollowJointTrajectory
    #   joints:
    #       - oberon7_r/finger_left_joint
    #       - oberon7_r/finger_tip_left_joint
    #       - oberon7_r/finger_right_joint
    #       - oberon7_r/finger_tip_right_joint
    # - name: arm_position_l
    #   action_ns: follow_joint_trajectory
    #   type: FollowJointTrajectory
    #   joints:
    #       - oberon7_l/azimuth
    #       - oberon7_l/shoulder
    #       - oberon7_l/elbow
    #       - oberon7_l/roll
    #       - oberon7_l/pitch
    #       - oberon7_l/wrist
    # - name: hand_position_l
    #   action_ns: follow_joint_trajectory
    #   type: FollowJointTrajectory
    #   joints:
    #       - oberon7_l/finger_left_joint
    #       - oberon7_l/finger_tip_left_joint
    #       - oberon7_l/finger_right_joint
    #       - oberon7_l/finger_tip_right_joint
    - name: arm_effort_r
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      joints:
          - perseus_r/Rev3
          - perseus_r/Rev5
          - perseus_r/Rev7
          - perseus_r/Rev9
    - name: gripper_effort_r
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      joints:
          - perseus_r/Slider16
          - perseus_r/Slider17
    - name: arm_effort_l
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      joints:
          - perseus_l/Rev3
          - perseus_l/Rev5
          - perseus_l/Rev7
          - perseus_l/Rev9
    - name: gripper_effort_l
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      joints:
          - perseus_l/Slider16
          - perseus_l/Slider17
