controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - perseus/Rev3
      - perseus/Rev5
      - perseus/Rev7
      - perseus/Rev9
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - perseus/Slider16
      - perseus/Slider17
initial:  # Define initial robot poses per group
#  - group: arm
#    pose: home

  []